name: Monitor LATAM Milhas

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4

      - name: Rodar monitor
        run: python monitor_latam.py
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
