name: Monitor LATAM Milhas

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências Python
        run: |
          pip install requests beautifulsoup4

      - name: Rodar monitor de milhas
        run: python monitor_latam.py
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT:  ${{ secrets.TG_CHAT }}
